### ISSUE TITLE
Complete bold sentence disappears after removing the first word 

### ISSUE THREAD

**Issue by watzak** [upfrontIO/editable.js#108]
Scenario to reproduce on http://upfrontio.github.io/editable.js/examples/:
1.) Mark a sentence and set this content to bold!
2.) Select the first word
3.) Remove this first word with backspace
4.) Bug: Not only the first bold word disappears, also the complete bold sentence

![bug](https://cloud.githubusercontent.com/assets/8505970/10134470/4a9f8008-65e6-11e5-9f34-16bc441da158.gif)

**Comment by watzak** [comment]
JFYI: Actually the issue also appears with italic tag ;)

**Comment by watzak** [comment]
These bugs only appear in chrome
With firefox everything is ok ;)

**Comment by watzak** [comment]
Think u do not have to use following method anymore (preventContenteditableBug in keyboard.js)
Then it should work ;)

**Comment by marcbachmann** [comment]
@peyerluk can't find any changes on the current behavior in the chromium issues.
https://bugs.chromium.org/p/chromium/issues/list?can=1&q=contenteditable&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

But it really looks like the span bug workaround causes the problem.

**Comment by peyerluk** [comment]
... or a different solution to the span bug.

**Comment by marcbachmann** [comment]
Maybe they have fixed that span insert bug in newer blink versions.
