### ISSUE TITLE
Behaviour of dispatcher's `isInputEventSupported`

### ISSUE THREAD

**Issue by nephridium** [upfrontIO/editable.js#139]
The Boolean `isInputEventSupported` is currently [initialized as `false`](https://github.com/upfrontIO/editable.js/blob/e2f6d76f1557123dbaf866b37246032d7bf5f919/src/dispatcher.js#L13), but [set to `true`](https://github.com/upfrontIO/editable.js/blob/e2f6d76f1557123dbaf866b37246032d7bf5f919/src/dispatcher.js#L118-L121) when an `input.editable` event comes in. This means there is [different behaviour of `triggerChangeEvent()`](https://github.com/upfrontIO/editable.js/blob/e2f6d76f1557123dbaf866b37246032d7bf5f919/src/dispatcher.js#L140-L148) depending on whether or not an `input.editable` event has occurred yet.

I've bumped into this because I'm currently using `triggerChangeEvent()` to inform the framework of a change.

Imho `isInputEventSupported` should be initialized/set only once depending on the browser's capabilities. @peyerluk what do you think?

**Comment by peyerluk** [comment]
I didn't find a way to feature detect `isInputEventSupported` without waiting for an acutal user input.
